sudo: required

languages: php
php:
  - 5.6

services:
  - docker

before_install:
  - docker pull say0213/wordpress

install:
  - echo "install"
before_script:
  - echo " befor_scriptやで"
script:
  - echo "scriptやで"
after_success:
  - echo "after_successやで"
after_failure:
  - echo "🍣"

after_script:
  - echo "after_scriptやで"
