language: php
php:
  - 5.5

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

before_script:

script:
    - mkdir -p build/logs
    - phpunit --coverage-clover build/logs/clover.xml --configuration tests/phpunit.xml tests

after_success:
    - travis_rtry php vendor/bin/coveralls -v
